name: clemency
description: Weather project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  provider: ^6.0.3
  flutter_spinkit: ^5.1.0
  geolocator: ^9.0.2
  location: ^4.2.0
  http: ^0.13.5
  firebase_messaging: ^13.0.3
  firebase_core: ^1.23.0
  flutter_local_notifications: ^11.0.1
  upgrader: ^4.6.1
  fluttericon: ^2.0.0
  uuid: ^3.0.6
  modal_progress_hud: ^0.1.3
  modal_progress_hud_nsn: ^0.3.0
  syncfusion_flutter_gauges: ^20.3.50
  get: ^4.6.5
  intl: ^0.17.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Poppins
       fonts:
           - asset: fonts/Poppins-Black.ttf
           - asset: fonts/Poppins-Medium.ttf

  #         style: italic

     - family: Barlow
       fonts:
            - asset: fonts/Barlow.ttf


  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
